extends:
  - eslint:recommended
  - airbnb-base

env:
  es6: false

parserOptions:
  sourceType: script

rules:
  # Best Practices
  no-eval: off
  no-param-reassign: off
  no-unused-expressions: warn
  vars-on-top: off
  yoda: off

  # Strict Mode
  strict:
    - error
    - global

  # Stylistic Issues
  max-len: off
  no-mixed-operators: off
  no-multi-assign: off
  no-plusplus: off
  no-underscore-dangle: off
  space-before-function-paren:
    - error
    - never

  # ESMAScript 6
  no-var: off
  object-shorthand: off
  prefer-template: off

  # plugin: import
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
